### ISSUE TITLE
error on registration

### ISSUE THREAD

**Issue by gabru-md** [tech4GT/fes-portal#5]
![screenshot at 2017-10-05 10-48-05](https://user-images.githubusercontent.com/25414121/31221196-ca89e8fc-a9ba-11e7-813e-8570dc6b52b1.png)

I encountered this error when i tried to register as a new user. I don't think that it is because of different databases.
Please have a look. @tech4GT

**Comment by tech4GT** [comment]
It is because you are trying to create a user without name

**Comment by tech4GT** [comment]
Please note Every field has first character capitalized. Name Bio and so on

**Comment by gabru-md** [comment]
![as](https://user-images.githubusercontent.com/25414121/31222660-d452769c-a9bf-11e7-92db-e66b9511f759.png)

This is what I've been entering and in any case if i had missed out the name then there would have been a flash message notifying me. So I definitely did not miss the name in above case.
Please have a look at it

**Comment by gabru-md** [comment]
maybe just a database error.
works fine as i changed to PostgreSQL
